# Generated by Django 4.2.4 on 2023-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='formatted_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
