# Generated by Django 4.2.4 on 2023-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_formatted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='formatted_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
