# Generated by Django 4.2.4 on 2023-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_cart_price_cart_formatted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='formatted_price',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='formatted_price',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
