# Generated by Django 4.2.4 on 2023-08-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_formatted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='formatted_price',
        ),
    ]
