# Generated by Django 4.2.4 on 2023-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='formatted_price',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
