# Generated by Django 4.2.4 on 2023-08-26 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_formatted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='volume',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
