# Generated by Django 4.2.4 on 2023-08-26 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='volume',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
